from fpdf import FPDF
import datetime

class PDFReportGenerator(FPDF):
    """Generates a professional legal analysis report with a Summary Table"""
    
    def header(self):
        self.set_font('helvetica', 'B', 10)
        self.set_text_color(100, 100, 100)
        self.cell(0, 10, 'CONFIDENTIAL: AI-ASSISTED CONTRACT REVIEW', 0, 1, 'R')
        self.ln(5)

    def footer(self):
        self.set_y(-15)
        self.set_font('helvetica', 'I', 8)
        self.set_text_color(128, 128, 128)
        self.cell(0, 10, f'Page {self.page_no()} | Generated by Mistral Legal Specialist', 0, 0, 'C')

    def generate(self, contract_name, analysis_results):
        # Initialize PDF
        self.add_page()
        
        # --- TITLE SECTION ---
        self.set_font('helvetica', 'B', 22)
        self.set_text_color(26, 54, 93) 
        self.cell(0, 15, 'Contract Analysis Executive Summary', 0, 1, 'L')
        
        self.set_font('helvetica', '', 10)
        self.set_text_color(0, 0, 0)
        self.cell(0, 6, f"Document Name: {contract_name}", 0, 1, 'L')
        self.cell(0, 6, f"Report Date: {datetime.datetime.now().strftime('%d %B %Y %H:%M')}", 0, 1, 'L')
        self.ln(10)

        # --- SECTION 1: COMPLIANCE SUMMARY TABLE ---
        if 'compliance_results' in analysis_results:
            self.set_font('helvetica', 'B', 14)
            self.cell(0, 10, '1. Compliance Overview Matrix', 0, 1, 'L')
            self.ln(2)
            
            # Table Header
            self.set_font('helvetica', 'B', 10)
            self.set_fill_color(230, 230, 230)
            self.cell(15, 10, 'ID', 1, 0, 'C', fill=True)
            self.cell(100, 10, 'Compliance Rule', 1, 0, 'L', fill=True)
            self.cell(40, 10, 'Status', 1, 0, 'C', fill=True)
            self.cell(35, 10, 'Severity', 1, 1, 'C', fill=True)

            # Table Rows
            self.set_font('helvetica', '', 9)
            for res in analysis_results['compliance_results']:
                status = res.get('status', 'N/A')
                if status == "NON-COMPLIANT":
                    self.set_text_color(200, 0, 0) # Red
                elif status == "PARTIAL":
                    self.set_text_color(255, 140, 0) # Orange
                elif status == "COMPLIANT":
                    self.set_text_color(0, 128, 0) # Green
                else:
                    self.set_text_color(100, 100, 100) # Gray

                self.cell(15, 8, str(res.get('rule_id', '')), 1, 0, 'C')
                self.cell(100, 8, str(res.get('rule_name', '')), 1, 0, 'L')
                self.cell(40, 8, status, 1, 0, 'C')
                
                self.set_text_color(0, 0, 0)
                self.cell(35, 8, str(res.get('severity', 'medium')).upper(), 1, 1, 'C')
            
            self.ln(10)

        # --- SECTION 2: KEY SUMMARIES ---
        if 'key_clauses' in analysis_results:
            self.set_font('helvetica', 'B', 14)
            self.cell(0, 10, '2. Key Clause Detailed Summaries', 0, 1, 'L')
            self.ln(3)
            
            # FIX: key_clauses is a LIST of DICTS, not a DICT
            for item in analysis_results['key_clauses']:
                name = item.get('rule_name', 'Clause')
                summary = item.get('summary', 'No summary generated.')
                
                self.set_font('helvetica', 'B', 11)
                self.set_fill_color(245, 247, 250)
                self.cell(0, 8, f"  {name}", 0, 1, 'L', fill=True)
                
                self.set_font('helvetica', '', 10)
                # Multi-cell handles text wrapping for long summaries
                self.multi_cell(0, 6, summary)
                self.ln(4)

        # --- SECTION 3: RISK & RECOMMENDATIONS ---
        if 'risk_results' in analysis_results:
            self.add_page()
            self.set_font('helvetica', 'B', 14)
            self.cell(0, 10, '3. Business Risk & De-risking Strategy', 0, 1, 'L')
            self.ln(5)

            effective_page_width = self.epw

            for risk in analysis_results.get('risk_results', []):
                # 1. Header Box
                self.set_x(self.l_margin) # 🔥 ENSURE LEFT ALIGNMENT
                self.set_font('helvetica', 'B', 11)
                lvl = risk.get('risk_level', 'LOW').upper()
                risk_color = (255, 235, 235) if lvl == "HIGH" else (255, 250, 230)
                self.set_fill_color(*risk_color)
                
                cat = risk.get('category') or risk.get('rule_name', 'General')
                self.cell(effective_page_width, 8, f"Category: {cat} | Level: {lvl}", 1, 1, 'L', fill=True)
                
                # 2. Impact Section
                self.set_x(self.l_margin) 
                self.set_font('helvetica', '', 10)
                impact_text = f"Business Impact: {risk.get('business_impact', 'N/A')}"
                self.multi_cell(effective_page_width, 6, impact_text, border='LR', align='L')
                
                # 3. Recommendation Section
                self.set_x(self.l_margin) 
                self.set_font('helvetica', 'B', 10)
                self.set_fill_color(230, 245, 255) 
                reco_text = f"Strategic Recommendation: {risk.get('recommendation', 'N/A')}"
                
                # Use effective_page_width and explicit border to lock it in place
                self.multi_cell(effective_page_width, 6, reco_text, border=1, align='L', fill=True)
                
                self.ln(6)

        return self.output()